"""add phone no to users table

Revision ID: 367b34940c12
Revises: faff189af783
Create Date: 2022-02-19 21:22:38.990200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367b34940c12'
down_revision = 'faff189af783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
